modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "quickbackupmulti_webui"
version = "${version}"
displayName = "QuickBakcupMulti-Reforged-WebUI"
authors = "SkyDynamic"
description = '''
A extension mod for QuickBackupMulti Reforged that adds a web user interface for managing backups.
'''
#logoFile = ""

[[dependencies.quickbackupmulti_webui]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quickbackupmulti_webui]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.quickbackupmulti_webui]]
modId = "quickbakcupmulti_reforged"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"


